import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { parseDirectoryListing } from '@core/fs/listing-parser';

/**
 * The fixture is a real capture from Chrome, regenerated by
 * `tests/e2e/capture-listing.spec.ts`. Testing against a guessed format is
 * how this parser was wrong the first time.
 */
const REAL_LISTING = readFileSync('tests/fixtures/chrome-directory-listing.html', 'utf8');

const row = (
  name: string,
  url: string,
  isdir: 0 | 1,
  size: number,
  sizeText: string,
  epoch: number,
) =>
  `<script>addRow("${name}","${url}",${isdir},${size},"${sizeText}",${epoch},"x");</script>`;

const page = (rows: string) =>
  `<!DOCTYPE html><html><head><script>function addRow(name, url, isdir,
    size, size_string, date_modified, date_modified_string) {}</script></head>
   <body><table id="tbody"></table>${rows}</body></html>`;

describe('parseDirectoryListing — against a real Chrome capture', () => {
  const entries = parseDirectoryListing(REAL_LISTING, '/tmp/tree');

  it('parses the capture', () => {
    expect(entries).not.toBeNull();
  });

  it('finds every entry and nothing else', () => {
    expect(entries!.map((e) => e.name).sort()).toEqual([
      'docs',
      'my notes',
      'notes.txt',
      'readme.md',
      '設定.md',
    ]);
  });

  it('distinguishes directories from files', () => {
    const byName = Object.fromEntries(entries!.map((e) => [e.name, e]));
    expect(byName['docs']!.kind).toBe('directory');
    expect(byName['my notes']!.kind).toBe('directory');
    expect(byName['readme.md']!.kind).toBe('file');
    expect(byName['設定.md']!.kind).toBe('file');
  });

  it('reads exact byte sizes for files and none for directories', () => {
    const byName = Object.fromEntries(entries!.map((e) => [e.name, e]));
    expect(byName['readme.md']!.size).toBe(9);
    expect(byName['notes.txt']!.size).toBe(5);
    // Chrome reports 0 for directories, which is a placeholder, not a fact.
    expect(byName['docs']!.size).toBeNull();
  });

  it('converts the epoch-seconds timestamp to milliseconds', () => {
    // Read the expected value out of the fixture rather than hardcoding it:
    // the capture spec regenerates this file with fresh timestamps.
    // Anchored on the full argument list: a lazy match would stop at the
    // size field, which is also a bare number.
    const match = REAL_LISTING.match(
      /addRow\("readme\.md","[^"]*",\d+,\d+,"[^"]*",(\d+),/,
    )!;
    const epochSeconds = Number(match[1]);

    const entry = entries!.find((e) => e.name === 'readme.md')!;
    expect(entry.modifiedAt).toBe(epochSeconds * 1000);
    // A plain epoch-seconds value would land in 1970; guard against that.
    expect(new Date(entry.modifiedAt!).getFullYear()).toBeGreaterThan(2000);
  });

  it('builds child paths under the directory', () => {
    const entry = entries!.find((e) => e.name === 'readme.md')!;
    expect(entry.path).toBe('/tmp/tree/readme.md');
  });

  it('keeps the decoded name, not the percent-encoded URL', () => {
    // Chrome passes both; the display name is the one users recognize.
    expect(entries!.map((e) => e.name)).toContain('設定.md');
    expect(entries!.map((e) => e.name)).toContain('my notes');
  });
});

describe('parseDirectoryListing — synthesized cases', () => {
  it('handles an empty folder', () => {
    expect(parseDirectoryListing(page(''), '/empty')).toEqual([]);
  });

  it('refuses a page that is not a directory listing', () => {
    // Returning [] here would tell the user the folder is empty, which is a
    // plausible lie. Null lets the caller report that it could not be read.
    expect(
      parseDirectoryListing('<html><body><h1>Hi</h1></body></html>', '/x'),
    ).toBeNull();
    expect(parseDirectoryListing('', '/x')).toBeNull();
  });

  it('skips . and .. if Chrome ever emits them', () => {
    const html = page(
      row('..', '..', 1, 0, '', 1700000000) +
        row('a.md', 'a.md', 0, 1, '1 B', 1700000000),
    );
    const entries = parseDirectoryListing(html, '/d')!;
    expect(entries.map((e) => e.name)).toEqual(['a.md']);
  });

  it('decodes escape sequences in names', () => {
    const html = page(
      `<script>addRow("quote\\"name.md","q.md",0,1,"1 B",1700000000,"x");</script>`,
    );
    expect(parseDirectoryListing(html, '/d')![0]!.name).toBe('quote"name.md');
  });

  it('handles a name containing a comma', () => {
    const html = page(row('a,b.md', 'a%2Cb.md', 0, 3, '3 B', 1700000000));
    expect(parseDirectoryListing(html, '/d')![0]!.name).toBe('a,b.md');
  });

  it('handles a name containing parentheses', () => {
    const html = page(row('doc (1).md', 'doc%20(1).md', 0, 3, '3 B', 1700000000));
    expect(parseDirectoryListing(html, '/d')![0]!.name).toBe('doc (1).md');
  });

  it('reports no timestamp when Chrome reports zero', () => {
    const html = page(row('a.md', 'a.md', 0, 1, '1 B', 0));
    expect(parseDirectoryListing(html, '/d')![0]!.modifiedAt).toBeNull();
  });

  it('joins paths correctly whether or not the directory ends in a slash', () => {
    const html = page(row('a.md', 'a.md', 0, 1, '1 B', 1700000000));
    expect(parseDirectoryListing(html, '/d')![0]!.path).toBe('/d/a.md');
    expect(parseDirectoryListing(html, '/d/')![0]!.path).toBe('/d/a.md');
  });

  it('scales to a large directory', () => {
    const rows = Array.from({ length: 5000 }, (_, i) =>
      row(`file-${i}.md`, `file-${i}.md`, 0, i, `${i} B`, 1700000000),
    ).join('');
    const entries = parseDirectoryListing(page(rows), '/big')!;
    expect(entries).toHaveLength(5000);
  });
});
